apiVersion: v1
kind: Pod
metadata:
  name: remote-dist-{{ replica }}-{{ uuid }}
  labels:
    app: remote-dist
    replica: "{{ replica }}"
    implementation: "{{ implementation }}"
    id: "{{ uuid }}"
    app.kubernetes.io/managed-by: implementation-provider
spec:
  containers:
  - name: remote-dist
    image: robertovrf/remote-dist:all
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 256Mi
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/ready
      initialDelaySeconds: 5
      periodSeconds: 5
    ports:
    - containerPort: 2011
    - containerPort: 2010
    env:
{{ env | to_yaml | indent(6, true) }}
