apiVersion: v1
kind: Service
metadata:
  name: remote-dist-{{ replica }}-{{ uuid }}
  labels:
    app: remote-dist
    replica: "{{ replica }}"
    implementation: "{{ implementation }}"
    id: "{{ uuid }}"
    app.kubernetes.io/managed-by: implementation-provider
spec:
  ports:
  - port: 2011
    name: rdist
    targetPort: 2011
  - port : 2010
    name: serverapp
    targetPort: 2010
  selector:
    app: remote-dist
    replica: "{{ replica }}"
    id: "{{ uuid }}"
  type: LoadBalancer
