apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-admin
  namespace: default
secrets:
- name: admin-token
---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: admin-token
#   annotations:
#     kubernetes.io/service-account.name: cluster-admin
# type: kubernetes.io/service-account-token
# ---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: naive-rbac
subjects:
 - kind: ServiceAccount
   name: default
   namespace: default
 - kind: ServiceAccount
   name: cluster-admin
   namespace: default
roleRef:
 kind: ClusterRole
 name: cluster-admin
 apiGroup: rbac.authorization.k8s.io